version: '3'
services:
  sharelatex:
    volumes:
      - 'sharelatex-data:/var/lib/sharelatex'
  mongodb:
    volumes:
      - 'mongodb-data:/db/data'
  mysql:
    volumes:
      - 'mysql-data:/var/lib/data'
  transmission-oss:
    volumes:
      - D:/DockerTransmission/downloads:/var/lib/transmission-daemon/downloads
      - D:/DockerTransmission/watch:/var/lib/transmission-daemon/watch
      - D:/DockerTransmission/info/resume:/var/lib/transmission-daemon/info/resume
      - D:/DockerTransmission/info/torrents:/var/lib/transmission-daemon/info/torrents
  util:
    volumes:
      - 'D:/DockerBackups:/var/lib/backups'
      - 'D:/DockerGit:/var/lib/git'
    ports:
      - '22:22'
  resilio-server:
    volumes:
      - D:/DockerResilioSync/settings/.sync:/.sync
      - D:/DockerBackups:/var/lib/resilio-folders
  plex:
    volumes:
      - plex-config:/config

volumes:
  sharelatex-data:
    external: true
  mongodb-data:
    external: true
  mysql-data:
    external: true
  plex-config:
    external: true
