version: '3'
services:
  sharelatex:
    volumes:
      - '/var/lib/sharelatex:/var/lib/sharelatex'
  mongodb:
    volumes:
      - '/var/lib/mongodb/data:/data/db'
  mysql:
    volumes:
      - '/var/lib/mysql:/var/lib/data'
      - '/var/lib/backups/mysql:/var/lib/backup'
  transmission-oss:
    volumes:
      - '/var/lib/downloads/oss:/var/lib/downloads'
      - '/var/lib/transmission-oss:/var/lib/transmission-daemon'
  util:
    volumes:
      - '/var/lib/backups:/var/lib/backups'
      - '/var/lib/git:/var/lib/git'
    ports:
      - '22:22'
  resilio-server:
    volumes:
      - /var/lib/.sync:/.sync
      - /var/lib/backups:/var/lib/resilio-folders
  plex:
    volumes:
      - /var/lib/plex:/config
  factorio-server:
    volumes:
      - /var/lib/factorio:/var/lib/factorio/saves
