version: '3'
services:
  sharelatex:
    volumes:
      - 'sharelatex-data:/var/lib/sharelatex'
  mongodb:
    volumes:
      - 'mongodb-data:/db/data'
  unifi:
    volumes:
      - ~/Desktop/docker/unifi/data:/unifi/data
  mysql:
    volumes:
      - 'mysql-data:/var/lib/data'
  transmission-oss:
    volumes:
      - ~/Desktop/docker/transmission/downloads:/var/lib/transmission-daemon/downloads
      - ~/Desktop/docker/transmission/watch:/var/lib/transmission-daemon/watch
      - ~/Desktop/docker/transmission/info/resume:/var/lib/transmission-daemon/info/resume
      - ~/Desktop/docker/transmission/info/torrents:/var/lib/transmission-daemon/info/torrents
  util:
    volumes:
      - '~/Desktop/docker/backups:/var/lib/backups'
      - '~/Desktop/docker/git:/var/lib/git'
    ports:
      - '2000:22'
  resilio-server:
    volumes:
      - ~/Desktop/docker/resilio:/.sync
      - ~/Desktop/docker/backups:/var/lib/resilio-folders
  plex:
    volumes:
      - plex-config:/config

volumes:
  sharelatex-data:
    external: true
  mongodb-data:
    external: true
  mysql-data:
    external: true
  plex-config:
    external: true
