version: '3'
services:
  sharelatex:
    volumes:
      - '${HOST_DATA_DIR?HOST_DATA_DIR}/sharelatex:/var/lib/sharelatex'
  mongodb:
    volumes:
      - '${HOST_DATA_DIR?HOST_DATA_DIR}/mongodb/data:/data/db'
  mysql:
    volumes:
      - '${HOST_DATA_DIR?HOST_DATA_DIR}/mysql:/var/lib/data'
  util:
    ports:
      - '22:22'
  plex:
    volumes:
      - '${HOST_DATA_DIR?HOST_DATA_DIR}/plex:/config'
  openvpn-as:
    volumes:
      - '${HOST_DATA_DIR?HOST_DATA_DIR}/openvpn-as:/config'
